name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - jupyter
  - joblib
  - requests
  - tqdm
  - shapely
  - descartes
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - root
  - scipy
